// Generated by gencpp from file package_rostocan/apps.msg
// DO NOT EDIT!


#ifndef PACKAGE_ROSTOCAN_MESSAGE_APPS_H
#define PACKAGE_ROSTOCAN_MESSAGE_APPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_rostocan
{
template <class ContainerAllocator>
struct apps_
{
  typedef apps_<ContainerAllocator> Type;

  apps_()
    : pedal_position(0)
    , counter(0)
    , position_diff(0)  {
    }
  apps_(const ContainerAllocator& _alloc)
    : pedal_position(0)
    , counter(0)
    , position_diff(0)  {
  (void)_alloc;
    }



   typedef uint16_t _pedal_position_type;
  _pedal_position_type pedal_position;

   typedef uint8_t _counter_type;
  _counter_type counter;

   typedef int8_t _position_diff_type;
  _position_diff_type position_diff;





  typedef boost::shared_ptr< ::package_rostocan::apps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_rostocan::apps_<ContainerAllocator> const> ConstPtr;

}; // struct apps_

typedef ::package_rostocan::apps_<std::allocator<void> > apps;

typedef boost::shared_ptr< ::package_rostocan::apps > appsPtr;
typedef boost::shared_ptr< ::package_rostocan::apps const> appsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_rostocan::apps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_rostocan::apps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_rostocan::apps_<ContainerAllocator1> & lhs, const ::package_rostocan::apps_<ContainerAllocator2> & rhs)
{
  return lhs.pedal_position == rhs.pedal_position &&
    lhs.counter == rhs.counter &&
    lhs.position_diff == rhs.position_diff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_rostocan::apps_<ContainerAllocator1> & lhs, const ::package_rostocan::apps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_rostocan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_rostocan::apps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_rostocan::apps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_rostocan::apps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_rostocan::apps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_rostocan::apps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_rostocan::apps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_rostocan::apps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d6478f1da74e05ce29749e8a7519384";
  }

  static const char* value(const ::package_rostocan::apps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d6478f1da74e05cULL;
  static const uint64_t static_value2 = 0xe29749e8a7519384ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_rostocan::apps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_rostocan/apps";
  }

  static const char* value(const ::package_rostocan::apps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_rostocan::apps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 pedal_position\n"
"uint8 counter\n"
"int8 position_diff\n"
;
  }

  static const char* value(const ::package_rostocan::apps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_rostocan::apps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pedal_position);
      stream.next(m.counter);
      stream.next(m.position_diff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct apps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_rostocan::apps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_rostocan::apps_<ContainerAllocator>& v)
  {
    s << indent << "pedal_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pedal_position);
    s << indent << "counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.counter);
    s << indent << "position_diff: ";
    Printer<int8_t>::stream(s, indent + "  ", v.position_diff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_ROSTOCAN_MESSAGE_APPS_H
